### PR TITLE
color list item: add copy animation

### PR DESCRIPTION
**Pull request by legomushroom**

### CODE REVIEW

**Comment by lukeed** [comment]
Cool! Thanks!! 😀 

I might remove the copy icon if that's okay with you?

**Comment by legomushroom** [comment]
Animation without the icon doesn't make much sense for me cuz it will be just a ripple but I'm totally ok if you want to remove it :)

**Comment by lukeed** [comment]
I feel like it'll make sense because of the "Copied" message that slides down?

**Comment by legomushroom** [comment]
Without the icon, the animation just shows interaction with the component and it doesn't convey that it was copied. The message can help, but it shows up unevenly when you click randomly on the elements so it might be confusing. If we can show the message each time user click on the component, it will be ok I guess. It might take more effort from the user to associate this two events but probably will do just fine.

**Pull request merged**
